package com.yin.myproject.practice.util.error;

public enum ErrorCode {

	AUDIT_TYPE_NULL("AUDIT_TYPE_NULL", "未选择审核状态"),

	USER_UNLOGIN("USER_UNLOGIN", "用户未登录,或连接超时"),

	BAD_REQUEST("BAD_REQUEST", "请求数据不完整"),

	DATA_CONFLICT("DATA_CONFLICT", "数据重复"),

	USER_PHONE_CONFLICT("USER_PHONE_CONFLICT", "用户电话重复"),

	USER_NAME_CONFLICT("USER_NAME_CONFLICT", "用户名重复"),

	ERR_SERVER_EXCEPTION("ERR_SERVER_EXCEPTION", "对不起,服务器繁忙,请稍候再试"),

	ERR_MISS_ENTITY("ERR_MISS_ENTITY", "主体缺失"),

	ERR_CREATE_ENTITY("ERR_CREATE_ENTITY", "不能创建数据对象"),

	NULL_ACCOUNT("NULL_ACCOUNT", "没有登录信息"),

	NOT_FIND_ACCOUNT("NOT_FIND_ACCOUNT", "用户不存在"),

	PASSORD_ERROR("PASSORD_ERROR", "密码错误"),

	VERIFY_FAIL("VERIFY_FAIL", "验证数据签名错误"),

	MAPPER_ERROR("MAPPER_ERROR", "对象转换错误"),

	NULL_PAYCOMPANY("NULL_PAYCOMPANY", "没有传入支付公司名称"),

	NULL_AMOUNT("NULL_AMOUNT", "金额为空"),

	NOT_FOUND_RECORD("NOT_FOUND_RECORD", "没有找到对应的数据记录"),

	SAVE_FAIL("SAVE_FAIL", "保存数据失败"),

	MAX_ADUIT_AMOUNT("MAX_ADUIT_AMOUNT", "单笔审核额度不得大于1000万"),

	CREDIT_AMOUNT("CREDIT_AMOUNT", "信用额度不够"),

	NOT_ALLOW_LOAN("NOT_ALLOW_LOAN", "您还有未完成的借款，目前不允许投标"),

	NOT_ALLOW_AUDIT("NOT_ALLOW_AUDIT", "不允许审核该标"),

	PAYCOMPANY_ERROR("PAYCOMPANY_ERROR", "调用支付公司错误"),

	IMAGE_VALIDATOR_ERROR("NOT_ACCEPTABLE", "验证码错误"),

	PHONE_VALIDATOR_ERROR("PHONE_VALIDATOR_ERROR", "手机验证码错误"),

	ACCOUNT_NOT_ENOUGH("ACCOUNT_NOT_ENOUGH", "帐户余额不足"),

	ERR_ACCOUNT_FROZEN("ERR_ACCOUNT_FROZEN", "帐户被冻结"),

	NULL_INVEST_BEGIN_LOAN("NULL_INVEST_BEGIN_LOAN", "未找到投资记录"),

	NO_DATA_AVAILABLE("NO_DATA_AVAILABLE", "无有效数据"),

	SUBTRACT_AMOUNT_ERROR("SUBTRACT_AMOUNT_ERROR", "减少资金大于实际资金"),

	ERR_DOMAIN_BUILD("ERR_DOMAIN_BUILD", "域模型组装异常"),

	USER_CONFIRMED_ERROR("USER_CONFIRMED_ERROR", "用户已认证"),

	USER_UNCONFIRMED_ERROR("USER_UNCONFIRMED_ERROR", "用户未实名认证"),

	UNLOCK_MONEY_ERROR("UNLOCK_MONEY_ERROR", "解锁金额大于锁定金额"),

	ERR_USER_GETBYPHONE_NOT_FOUND("ERR_USER_GETBYPHONE_NOT_FOUND", "没有发现该电话号码的用户"),

	ERR_APPCODE_MISSING("ERR_APPCODE_MISSING", "注册码丢失"),

	ERR_MESSAGENO_MISSING("ERR_MESSAGENO_MISSING", "消息码丢失"),

	ERR_MESSAGEBODY_MISSING("ERR_MESSAGEBODY_MISSING", "消息体丢失"),

	ERR_APPCODE_VALUE("ERR_APPCODE_VALUE", "注册码不是P2P"),

	ERR_BINDINGLOAN_MISSING("ERR_BINDINGLOAN_MISSING", "传入参数为空"),

	ERR_SERVICE_NOT_FOUND("ERR_SERVICE_NOT_FOUND", "垫付宝没有该用户信息"),

	ERR_FULLNAME_VALUE("ERR_FULLNAME_VALUE", "用户名称不存在"),

	ERR_PHONE_VALUE("ERR_PHONE_VALUE", "用户电话号码不存在"),

	ERR_IDCARDCODE_VALUE("ERR_IDCARDCODE_VALUE", "身份证有错误"),

	ERR_USER_GETBYID_NOT_FOUND("ERR_USER_GETBYID_NOT_FOUND", "没有发现该用户"),

	ERR_VERIFYCODE_NOT_FOUND("ERR_VERIFYCODE_NOT_FOUND", "用户验证码没发现"),

	ERR_CARD_GETBYUSERID_NOT_FOUND("ERR_CARD_GETBYUSERID_NOT_FOUND", "没用该垫付卡的用户信息"),

	ERR_VERIFYCODE_VALUE("ERR_VERIFYCODE_VALUE", "验证码错误"),

	ERR_PASSWORD_VALUE("ERR_PASSWORD_VALUE", "用户密码错误"),

	ERR_USER_BINDED_FOR_KYPAY("ERR_USER_BINDED_FOR_KYPAY", "P2P保存垫付宝用户信息失败！"),

	ALREADY_CREDITING_ERROR("ALREADY_CREDITING_ERROR", "已经申请授信"),

	ALREADY_CREDITED_ERROR("ALREADY_CREDITED_ERROR", "已经授信成功"),

	ALREADY_INVITE("ALREADY_INVITE", "已经被邀请"),

	DECODE_ERROR("DECODE_ERROR", "解码异常"),

	NOT_USER_ERROR("NOT_USER_ERROR", "没有这个用户"),

	SAME_REPSD_ERROR("SAME_REPSD_ERROR", "重置密码和确认密码不相同"),

	INVITECODE_ERROR("INVITECODE_ERROR", "邀请码异常"),

	KYPAY_ACCOUNT_CONFLIECT("KYPAY_ACCOUNT_CONFLIECT", "执付宝帐户已绑定"),

	KYPAY_AKKA_ERROR("KYPAY_ERROR", "连接垫付宝错误"),

	KYPAY_ERROR("KYPAY_ERROR", "垫付宝操作错误"),

	KYPAY_COUNT_NOT_FOUND("KYPAY_COUNT_NOT_FOUND", "垫付宝账户不存在"),

	SIGN_CONTRACT_ERROR("SIGN_CONTRACT_ERROR", "垫付宝未签约"),

	SAME_OLDEMAIL_ERROR("SAME_OLDEMAIL_ERROR", "邮箱重复"),

	SAME_OLDPSD_ERROR("SAME_OLDPSD_ERROR", "原始密码和新密码重复"),

	IDENTITY_ERROR("IDENTITY_ERROR", "该用户无此身份访问"),

	OLDPSD_ERROR("OLDPSD_ERROR", "原密码错误"),

	LOAN_STATUS_ERROR("LOAN_STATUS_ERROR", "借款状态不正确,请联系系统管理员或稍候再试"),

	HOLD_AMOUNT_NOT_ENOUGH("HOLD_AMOUNT_NOT_ENOUGH", "操作异常,您持有的额度不足,请重试"),

	ASSIGNMENT_IS_TRANSFERING("ASSIGNMENT_IS_TRANSFERING", "您的债券正在交易中,请稍候再试"),

	BUYER_AND_SELLER_IS_SAME_PERSON("BUYER_AND_SELLER_IS_SAME_PERSON", "不能购买自己的债券"),

	NO_POWER_BUY_ASSIGNMENT("NO_POWER_BUY_ASSIGNMENT", "不能购买该债券"),

	UN_SUPPORT_BUY_LEFT_AMOUNT("UN_SUPPORT_BUY_LEFT_AMOUNT", "不支持余额购买"),

	NOT_SUFFICIENT_FUNDS("NOT_SUFFICIENT_FUNDS", "您购买的债权额度不足"),

	ERR_SERVICEACCOUNT_NOT_COMPANY("ERR_SERVICEACCOUNT_NOT_COMPANY", "该用户不是垫付宝的企业用户"),

	KYPAY_LOCKED("KYPAY_LOCKED", "向P2P发送锁请求后，没有返回值或锁失败"),

	WITHDRAWAL_AMOUNT_ERROR("WITHDRAWAL_AMOUNT_ERROR", "提现金额 <=0,垫付宝不约束提现额度"),

	ERR_UPDATE_ACCOUNT("ERR_UPDATE_ACCOUNT", "修改垫付宝账户失败"),

	ERR_USER_EXIST("ERR_USER_EXIST", "该垫付宝已被签约"),

	ERR_DB_LOANCONFIRM_MISS("ERR_DB_LOANCONFIRM_MISS", "数据库中不存在数据"),

	ERR_VERISION_NOT_EQUAL("ERR_VERISION_NOT_EQUAL", "传入的版本信息不匹配"),

	ERRORCODE_NOT_EXIST("ERRORCODE_ERROR", "轻易贷中错误码不存在"),

	ERR_CREATE_KYLINKER("ERR_CREATE_KYLINKER", "创建KyLinker表失败"),

	ALREADY_OPERATE_TASK_ERROR("ALREADY_OPERATE_TASK_ERROR", "该任务已被认领"),

	ERR_DB_ACCOUNT_CARD_NOT_EXIT("ERR_DB_ACCOUNT_CARD_NOT_EXIT", "该用户的欠款方垫付宝账户不存在"),

	ERR_DB_KYLOANHISTORY_NOT_EXIT("ERR_DB_KYLOANHISTORY_NOT_EXIT", "该用户不存在历史账务在垫付宝1、2、3"),

	NETWORK_ERROR("NETWORK_ERROR", "网络服务出现问题");

	private String code;
	private String message;

	ErrorCode(String code, String message) {
		this.code = code;
		this.message = message;
	}

	public String getCode() {
		return code;
	}

	public String getMessage() {
		return message;
	}

	@Override
	public String toString() {
		return "ErrorCode{code=" + code + ", message='" + message + "'} ";
	}

}
